***
# Merge BTS, ASPM, and NOAA data

Create one departure-level table for the selected airport and year. BTS supplies the flight records and scheduled departure timestamp. ASPM supplies planned airport demand for the previous, current, and next clock hours. NOAA supplies the most recent weather report available at or before scheduled departure.

The next-hour ASPM values are scheduled counts known ahead of time, not future operating results. All three ASPM periods and the matched NOAA timestamp remain clearly named so their timing can be audited.
***

In [1]:
YEAR = 2019

AIRPORT = "JFK"
# AIRPORT = "ORD"
# AIRPORT = "ATL"

NOAA_TOLERANCE = "90min"

***
## Load the cleaned source files

Load the validated BTS, ASPM, and NOAA files. Parse the timestamp columns during loading so the joins use real datetimes rather than text.
***

In [2]:
from pathlib import Path

import pandas as pd

BTS_DATA_FILE = f"../data/bts/cleaned/{AIRPORT}_{YEAR}.csv"
ASPM_DATA_FILE = f"../data/aspm/cleaned/{AIRPORT}_{YEAR}.csv"
NOAA_DATA_FILE = f"../data/noaa/cleaned/{AIRPORT}_{YEAR}.csv"
MERGED_DATA_FILE = f"../data/merged/{AIRPORT}_{YEAR}.csv"

NOAA_TOLERANCE = pd.Timedelta(NOAA_TOLERANCE)

required_files = [BTS_DATA_FILE, ASPM_DATA_FILE, NOAA_DATA_FILE]
missing_files = [path for path in required_files if not Path(path).is_file()]

if missing_files:
    raise FileNotFoundError(
        "Run the clean notebooks first. Missing files: " + ", ".join(missing_files)
    )

bts = pd.read_csv(BTS_DATA_FILE, parse_dates=["FlightDate", "DATE"])
aspm = pd.read_csv(ASPM_DATA_FILE, parse_dates=["report_date", "DATE"])
noaa = pd.read_csv(NOAA_DATA_FILE, parse_dates=["DATE"])

aspm_columns = [
    "airport",
    "report_date",
    "Hour",
    "Scheduled Departures",
    "Scheduled Arrivals",
    "DATE",
]
missing_aspm_columns = [column for column in aspm_columns if column not in aspm.columns]
if missing_aspm_columns:
    raise KeyError(f"Missing required ASPM columns: {missing_aspm_columns}")
aspm = aspm[aspm_columns].copy()

pd.DataFrame({
    "rows": [len(bts), len(aspm), len(noaa)],
    "columns": [len(bts.columns), len(aspm.columns), len(noaa.columns)]
}, index=["BTS", "ASPM", "NOAA"])

        rows  columns
BTS   249428       28
ASPM    8760        6
NOAA   13094       18

***
## Validate the merge keys

Confirm that the required airport and timestamp fields are present and contain valid dates. ASPM must have one row per airport-hour. Exact duplicate NOAA timestamps are reported but retained; a stable sort means the last same-time report in source order is used by the backward as-of join.
***

In [3]:
required_columns = {
    "BTS": {"DATE", "FlightDate", "Origin", "Dest"},
    "ASPM": {"DATE", "airport", "report_date", "Hour"},
    "NOAA": {"DATE"}
}
source_frames = {"BTS": bts, "ASPM": aspm, "NOAA": noaa}

missing_columns = {
    name: sorted(columns - set(source_frames[name].columns))
    for name, columns in required_columns.items()
    if columns - set(source_frames[name].columns)
}

if missing_columns:
    raise KeyError(f"Missing merge columns: {missing_columns}")

invalid_dates = pd.Series({
    "BTS missing DATE": int(bts["DATE"].isna().sum()),
    "ASPM missing DATE": int(aspm["DATE"].isna().sum()),
    "NOAA missing DATE": int(noaa["DATE"].isna().sum())
})

if invalid_dates.sum() > 0:
    raise ValueError(f"Invalid merge timestamps:\n{invalid_dates}")

aspm_duplicate_keys = int(
    aspm.duplicated(subset=["airport", "DATE"], keep=False).sum()
)
if aspm_duplicate_keys > 0:
    raise ValueError(f"ASPM contains {aspm_duplicate_keys} duplicate airport-hour rows")

noaa_duplicate_timestamps = int(noaa["DATE"].duplicated(keep=False).sum())

pd.Series({
    "ASPM duplicate airport-hour rows": aspm_duplicate_keys,
    "NOAA rows with duplicate timestamps": noaa_duplicate_timestamps
}, name="merge-key validation")

ASPM duplicate airport-hour rows       0
NOAA rows with duplicate timestamps    8
Name: merge-key validation, dtype: int64

***
## Prepare airport departures and source timestamps

Keep flights departing from the selected airport because the available ASPM and NOAA records describe conditions at that origin. Give the retained ASPM fields short internal names before making separate previous-, current-, and next-hour copies. Rename the NOAA timestamp so the matched weather-report time remains clear.
***

In [4]:
bts_departures = bts.loc[bts["Origin"] == AIRPORT].copy()
bts_departures = bts_departures.sort_values("DATE", kind="stable").reset_index(drop=True)

aspm = aspm.rename(columns={
    "airport": "AIRPORT",
    "report_date": "REPORT_DATE",
    "Hour": "HOUR",
    "Scheduled Departures": "SCHEDULED_DEPARTURES",
    "Scheduled Arrivals": "SCHEDULED_ARRIVALS",
    "DATE": "DATE"
})

noaa = noaa.rename(columns={"DATE": "NOAA_DATE"})
noaa = noaa.sort_values("NOAA_DATE", kind="stable").reset_index(drop=True)

pd.Series({
    "all BTS rows": len(bts),
    f"{AIRPORT} departure rows": len(bts_departures),
    "non-origin rows excluded": len(bts) - len(bts_departures)
}, name="departure selection")

all BTS rows                249428
JFK departure rows          124759
non-origin rows excluded    124669
Name: departure selection, dtype: int64

***
## Join the previous, current, and next ASPM hours

For each scheduled departure, attach three ASPM schedule records based on the departure's clock hour. For example, a 14:35 departure uses 13:00 as the previous hour, 14:00 as the current hour, and 15:00 as the next hour.

Only planned arrival and departure counts are included. The next-hour record does not introduce leakage because it describes scheduled demand known ahead of time, not operations that occur in the future. Each period receives its own prefix, lookup timestamp, matched timestamp, and offset from scheduled departure.
***

In [5]:
aspm_period_offsets = {
    "PREVIOUS": -1,
    "CURRENT": 0,
    "NEXT": 1,
}

scheduled_departure_hour = bts_departures["DATE"].dt.floor("h")

for period, hour_offset in aspm_period_offsets.items():
    bts_departures[f"ASPM_{period}_LOOKUP_DATE"] = (
        scheduled_departure_hour + pd.Timedelta(hours=hour_offset)
    )

merged = bts_departures.copy()

for period in aspm_period_offsets:
    period_aspm = aspm.rename(columns={
        column: f"ASPM_{period}_{column}"
        for column in aspm.columns
    })

    merged = merged.merge(
        period_aspm,
        left_on=["Origin", f"ASPM_{period}_LOOKUP_DATE"],
        right_on=[f"ASPM_{period}_AIRPORT", f"ASPM_{period}_DATE"],
        how="left",
        validate="many_to_one"
    )

    merged[f"ASPM_{period}_OFFSET_MINUTES"] = (
        merged[f"ASPM_{period}_DATE"] - merged["DATE"]
    ).dt.total_seconds().div(60)

aspm_audit_columns = ["DATE"]
for period in aspm_period_offsets:
    aspm_audit_columns.extend([
        f"ASPM_{period}_LOOKUP_DATE",
        f"ASPM_{period}_DATE",
        f"ASPM_{period}_SCHEDULED_DEPARTURES",
        f"ASPM_{period}_SCHEDULED_ARRIVALS",
        f"ASPM_{period}_OFFSET_MINUTES",
    ])

merged[aspm_audit_columns].head()

,DATE,ASPM_PREVIOUS_LOOKUP_DATE,ASPM_PREVIOUS_DATE,ASPM_PREVIOUS_SCHEDULED_DEPARTURES,ASPM_PREVIOUS_SCHEDULED_ARRIVALS,ASPM_PREVIOUS_OFFSET_MINUTES,ASPM_CURRENT_LOOKUP_DATE,ASPM_CURRENT_DATE,ASPM_CURRENT_SCHEDULED_DEPARTURES,ASPM_CURRENT_SCHEDULED_ARRIVALS,ASPM_CURRENT_OFFSET_MINUTES,ASPM_NEXT_LOOKUP_DATE,ASPM_NEXT_DATE,ASPM_NEXT_SCHEDULED_DEPARTURES,ASPM_NEXT_SCHEDULED_ARRIVALS,ASPM_NEXT_OFFSET_MINUTES
0,2019-01-01 05:00:00,2019-01-01 04:00:00,2019-01-01 04:00:00,0,4,-60.0,2019-01-01 05:00:00,2019-01-01 05:00:00,10,25,0.0,2019-01-01 06:00:00,2019-01-01 06:00:00,23.0,19.0,60.0
1,2019-01-01 05:00:00,2019-01-01 04:00:00,2019-01-01 04:00:00,0,4,-60.0,2019-01-01 05:00:00,2019-01-01 05:00:00,10,25,0.0,2019-01-01 06:00:00,2019-01-01 06:00:00,23.0,19.0,60.0
2,2019-01-01 05:00:00,2019-01-01 04:00:00,2019-01-01 04:00:00,0,4,-60.0,2019-01-01 05:00:00,2019-01-01 05:00:00,10,25,0.0,2019-01-01 06:00:00,2019-01-01 06:00:00,23.0,19.0,60.0
3,2019-01-01 05:40:00,2019-01-01 04:00:00,2019-01-01 04:00:00,0,4,-100.0,2019-01-01 05:00:00,2019-01-01 05:00:00,10,25,-40.0,2019-01-01 06:00:00,2019-01-01 06:00:00,23.0,19.0,20.0
4,2019-01-01 05:45:00,2019-01-01 04:00:00,2019-01-01 04:00:00,0,4,-105.0,2019-01-01 05:00:00,2019-01-01 05:00:00,10,25,-45.0,2019-01-01 06:00:00,2019-01-01 06:00:00,23.0,19.0,15.0

***
## Join the latest available NOAA report

Use a backward as-of join to select the most recent NOAA observation at or before scheduled departure. The tolerance prevents a stale weather report from being carried forward more than 90 minutes. No future weather observation is allowed.
***

In [6]:
merged = merged.sort_values("DATE", kind="stable").reset_index(drop=True)

merged = pd.merge_asof(
    merged,
    noaa,
    left_on="DATE",
    right_on="NOAA_DATE",
    direction="backward",
    tolerance=NOAA_TOLERANCE,
    allow_exact_matches=True
)

merged["NOAA_AGE_MINUTES"] = (
    merged["DATE"] - merged["NOAA_DATE"]
).dt.total_seconds().div(60)

merged[["DATE", "NOAA_DATE", "NOAA_AGE_MINUTES"]].head()

                 DATE           NOAA_DATE  NOAA_AGE_MINUTES
0 2019-01-01 05:00:00 2019-01-01 04:51:00               9.0
1 2019-01-01 05:00:00 2019-01-01 04:51:00               9.0
2 2019-01-01 05:00:00 2019-01-01 04:51:00               9.0
3 2019-01-01 05:40:00 2019-01-01 04:51:00              49.0
4 2019-01-01 05:45:00 2019-01-01 04:51:00              54.0

***
## Validate the merged data

Confirm that the joins preserve the number of departure rows, all three ASPM records match their requested clock hours, and NOAA never comes from the future. The ASPM offsets should place the previous record 60–119 minutes before departure, the current record 0–59 minutes before departure, and the next record 1–60 minutes after departure. The positive next-hour offset is expected because its values are planned schedule counts.

Missing source matches are reported rather than silently removed. They may occur at a file boundary when the requested adjacent ASPM hour belongs to the preceding or following year.
***

In [7]:
merge_validation_values = {
    "BTS departure rows": len(bts_departures),
    "merged rows": len(merged),
    "row-count difference": len(merged) - len(bts_departures),
}

expected_aspm_offset_ranges = {
    "PREVIOUS": (-119, -60),
    "CURRENT": (-59, 0),
    "NEXT": (1, 60),
}

for period in aspm_period_offsets:
    matched_date = merged[f"ASPM_{period}_DATE"]
    lookup_date = merged[f"ASPM_{period}_LOOKUP_DATE"]
    offset_minutes = merged[f"ASPM_{period}_OFFSET_MINUTES"]
    minimum_offset, maximum_offset = expected_aspm_offset_ranges[period]

    merge_validation_values[f"missing ASPM {period.lower()} matches"] = int(
        matched_date.isna().sum()
    )
    merge_validation_values[f"ASPM {period.lower()} timestamp mismatches"] = int((
        matched_date.notna() & (matched_date != lookup_date)
    ).sum())
    merge_validation_values[f"ASPM {period.lower()} offsets outside expected range"] = int((
        offset_minutes.notna()
        & ~offset_minutes.between(minimum_offset, maximum_offset)
    ).sum())

merge_validation_values.update({
    "missing NOAA matches": int(merged["NOAA_DATE"].isna().sum()),
    "future NOAA matches": int((merged["NOAA_DATE"] > merged["DATE"]).sum()),
    "NOAA matches older than tolerance": int((
        merged["NOAA_AGE_MINUTES"] > NOAA_TOLERANCE.total_seconds() / 60
    ).sum()),
    "rows with duplicated BTS flight keys": int(merged.duplicated(
        subset=[
            "FlightDate", "Reporting_Airline",
            "Flight_Number_Reporting_Airline", "Origin", "Dest", "CRSDepTime"
        ],
        keep=False
    ).sum())
})

merge_validation = pd.Series(
    merge_validation_values,
    name="merged-data validation"
)

merge_validation

BTS departure rows                              124759
merged rows                                     124759
row-count difference                                 0
missing ASPM previous matches                        0
ASPM previous timestamp mismatches                   0
ASPM previous offsets outside expected range         0
missing ASPM current matches                         0
ASPM current timestamp mismatches                    0
ASPM current offsets outside expected range          0
missing ASPM next matches                            3
ASPM next timestamp mismatches                       0
ASPM next offsets outside expected range             0
missing NOAA matches                                 0
future NOAA matches                                  0
NOAA matches older than tolerance                    0
rows with duplicated BTS flight keys                 0
Name: merged-data validation, dtype: int64

In [8]:
timing_columns = [
    "ASPM_PREVIOUS_OFFSET_MINUTES",
    "ASPM_CURRENT_OFFSET_MINUTES",
    "ASPM_NEXT_OFFSET_MINUTES",
    "NOAA_AGE_MINUTES",
]

merged[timing_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
ASPM_PREVIOUS_OFFSET_MINUTES,124759.0,-88.896753,18.877087,-119.0,-105.0,-90.0,-73.0,-60.0
ASPM_CURRENT_OFFSET_MINUTES,124759.0,-28.896753,18.877087,-59.0,-45.0,-30.0,-13.0,0.0
ASPM_NEXT_OFFSET_MINUTES,124756.0,31.103274,18.876955,1.0,15.0,30.0,47.0,60.0
NOAA_AGE_MINUTES,124759.0,24.426061,16.846088,0.0,9.0,24.0,39.0,59.0

***
## Save the merged data

Create the merged-data directory when needed and save the departure-level dataframe without the pandas index. The clearly named previous-, current-, and next-hour ASPM fields, NOAA timestamp, and timing offsets are retained for later auditing and feature selection.
***

In [9]:
Path(MERGED_DATA_FILE).parent.mkdir(parents=True, exist_ok=True)
merged.to_csv(MERGED_DATA_FILE, index=False)

In [10]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124759 entries, 0 to 124758
Data columns (total 71 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   Year                                124759 non-null  int64
 1   Quarter                             124759 non-null  int64
 2   Month                               124759 non-null  int64
 3   DayofMonth                          124759 non-null  int64
 4   DayOfWeek                           124759 non-null  int64
 5   FlightDate                          124759 non-null  datetime64[ns]
 6   Reporting_Airline                   124759 non-null  object
 7   Tail_Number                         124759 non-null  object
 8   Flight_Number_Reporting_Airline     124759 non-null  int64
 9   Origin                              124759 non-null  object
 10  OriginState                         124759 non-null  object
 11  Dest                                124759 non-null  object
 12  DestState                           124759 non-null  object
 13  CRSDepTime                          124759 non-null  int64
 14  DepTime                             124759 non-null  float64
 15  DepDelay                            124759 non-null  float64
 16  DepDelayMinutes                     124759 non-null  float64
 17  DepDel15                            124759 non-null  float64
 18  DepartureDelayGroups                124759 non-null  float64
 19  TaxiOut                             124759 non-null  float64
 20  WheelsOff                           124759 non-null  float64
 21  CRSArrTime                          124759 non-null  int64
 22  ArrDel15                            124759 non-null  float64
 23  ArrivalDelayGroups                  124759 non-null  float64
 24  CRSElapsedTime                      124759 non-null  float64
 25  Distance                            124759 non-null  float64
 26  DistanceGroup                       124759 non-null  int64
 27  DATE                                124759 non-null  datetime64[ns]
 28  ASPM_PREVIOUS_LOOKUP_DATE           124759 non-null  datetime64[ns]
 29  ASPM_CURRENT_LOOKUP_DATE            124759 non-null  datetime64[ns]
 30  ASPM_NEXT_LOOKUP_DATE               124759 non-null  datetime64[ns]
 31  ASPM_PREVIOUS_AIRPORT               124759 non-null  object
 32  ASPM_PREVIOUS_REPORT_DATE           124759 non-null  datetime64[ns]
 33  ASPM_PREVIOUS_HOUR                  124759 non-null  int64
 34  ASPM_PREVIOUS_SCHEDULED_DEPARTURES  124759 non-null  int64
 35  ASPM_PREVIOUS_SCHEDULED_ARRIVALS    124759 non-null  int64
 36  ASPM_PREVIOUS_DATE                  124759 non-null  datetime64[ns]
 37  ASPM_PREVIOUS_OFFSET_MINUTES        124759 non-null  float64
 38  ASPM_CURRENT_AIRPORT                124759 non-null  object
 39  ASPM_CURRENT_REPORT_DATE            124759 non-null  datetime64[ns]
 40  ASPM_CURRENT_HOUR                   124759 non-null  int64
 41  ASPM_CURRENT_SCHEDULED_DEPARTURES   124759 non-null  int64
 42  ASPM_CURRENT_SCHEDULED_ARRIVALS     124759 non-null  int64
 43  ASPM_CURRENT_DATE                   124759 non-null  datetime64[ns]
 44  ASPM_CURRENT_OFFSET_MINUTES         124759 non-null  float64
 45  ASPM_NEXT_AIRPORT                   124756 non-null  object
 46  ASPM_NEXT_REPORT_DATE               124756 non-null  datetime64[ns]
 47  ASPM_NEXT_HOUR                      124756 non-null  float64
 48  ASPM_NEXT_SCHEDULED_DEPARTURES      124756 non-null  float64
 49  ASPM_NEXT_SCHEDULED_ARRIVALS        124756 non-null  float64
 50  ASPM_NEXT_DATE                      124756 non-null  datetime64[ns]
 51  ASPM_NEXT_OFFSET_MINUTES            124756 non-null  float64
 52  NOAA_DATE                           124759 non-null  datetime64[ns]
 53  HourlyDewPointTemperature           124759 non-null  float64
 54  HourlyDryBulbTemperature            124759 non-null  float64
 55  HourlyPrecipitation                 124759 non-null  float64
 56  HourlyRelativeHumidity              124759 non-null  float64
 57  HourlyVisibility                    124759 non-null  float64
 58  HourlyWindSpeed                     124759 non-null  float64
 59  Rain                                124759 non-null  int64
 60  Drizzle                             124759 non-null  int64
 61  Snow                                124759 non-null  int64
 62  Fog                                 124759 non-null  int64
 63  Mist                                124759 non-null  int64
 64  Thunderstorm                        124759 non-null  int64
 65  FreezingPrecip                      124759 non-null  int64
 66  Showers                             124759 non-null  int64
 67  PrecipOccurred                      124759 non-null  int64
 68  WindX                               124759 non-null  float64
 69  WindY                               124759 non-null  float64
 70  NOAA_AGE_MINUTES                    124759 non-null  float64
dtypes: datetime64[ns](12), float64(26), int64(24), object(9)
memory usage: 67.6+ MB

In [11]:
merged.isna().sum()

Year                0
Quarter             0
Month               0
DayofMonth          0
DayOfWeek           0
                   ..
Showers             0
PrecipOccurred      0
WindX               0
WindY               0
NOAA_AGE_MINUTES    0
Length: 71, dtype: int64

In [12]:
merged.loc[merged["ASPM_NEXT_AIRPORT"].isna()]

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,Tail_Number,Flight_Number_Reporting_Airline,Origin,...,Snow,Fog,Mist,Thunderstorm,FreezingPrecip,Showers,PrecipOccurred,WindX,WindY,NOAA_AGE_MINUTES
124756,2019,4,12,31,2,2019-12-31,B6,N283JB,486,JFK,...,0,0,0,0,0,0,0,17.0,3.122849e-15,9.0
124757,2019,4,12,31,2,2019-12-31,B6,N913JB,1503,JFK,...,0,0,0,0,0,0,0,17.0,3.122849e-15,41.0
124758,2019,4,12,31,2,2019-12-31,B6,N999JQ,839,JFK,...,0,0,0,0,0,0,0,15.0,2.755455e-15,7.0